name: 泅 Funkcionalitﾄ》es pievienoﾅ｡anas ziﾅojums
description: Ierosinﾄ》 jaunas funkcionalitﾄ》es pievienoﾅ｡anu.
labels: [Feature]
body:
  - type: textarea
    id: description
    attributes:
      label: Apraksti trﾅｫkstoﾅ｡o funkcionalitﾄ》i
      description: ﾄｪss un kodolﾄｫgs vﾄ斗amﾄ《 funkcionalitﾄ》es apraksts.
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Cita informﾄ…ija
      description: Papildus konteksts vai informﾄ…ija.
    validations:
      required: false
